; http://www.8bit-era.cz/6800.html

    .area MAIN ( REL )
    .globl LEVEL_INIT,LEVEL_SHOW,ROM_RESET,PLAYER_ANIM
    .globl CONTROL_INIT,CONTROL_A,CTRL_LEFT,CTRL_RIGHT,CTRL_UP,CTRL_DOWN,CTRL_RESTART,CTRL_EXIT,CTRL_N,CTRL_U ; From control
    .globl MOVE_LEFT,MOVE_RIGHT,MOVE_UP,MOVE_DOWN,MOVE_UNDO ; From player
    .globl GAME_INIT,LEVEL_INC,LEVEL_FINISHED ; From level
    .globl COPY_TO,COPY_FROM,COPY_FROM_TO_0 ; From copy
    .globl WAIT_FOR_YN_X_A ; From waitForYN
    .globl STATTEXT_LEVEL_ON_SCREEN ; From config
    .globl END_OF_LEVEL_EFFECT ; From sounf-effects
    .globl AJOY_INIT ; From ajoy

    JSR AJOY_INIT
    JSR GAME_INIT
    JSR CONTROL_INIT
RESTART_LEVEL:
    JSR LEVEL_INIT
NEXT: ; Next level start?
    JSR LEVEL_SHOW
MAIN_LOOP::
    TST LEVEL_FINISHED
    BNE NEXT_LEVEL
    JSR PLAYER_ANIM
    JSR CONTROL_A
    BEQ MAIN_LOOP
CHK_LEFT:
    CMPA #CTRL_LEFT
    BNE CHK_RIGHT
    JMP MOVE_LEFT
CHK_RIGHT:
    CMPA #CTRL_RIGHT
    BNE CHK_UP
    JMP MOVE_RIGHT
CHK_UP:
    CMPA #CTRL_UP
    BNE CHK_DOWN
    JMP MOVE_UP
CHK_DOWN:
    CMPA #CTRL_DOWN
    BNE CHK_U
    JMP MOVE_DOWN
CHK_U: ; Undo ?
    CMPA #CTRL_U
    BNE CHK_RESTART
    JMP MOVE_UNDO
CHK_RESTART:
    CMPA #CTRL_RESTART
    BNE CHK_N
    BRA RESTART_LEVEL
CHK_N: ; Next level ???
    CMPA #CTRL_N
    BNE MAIN_LOOP
    BRA MANUAL_NEXT_LEVEL
NEXT_LEVEL:
    JSR END_OF_LEVEL_EFFECT

    LDX #FINISH_TEXT
    STX COPY_FROM
    LDX #STATTEXT_LEVEL_ON_SCREEN+32     ; A szint sor eleje
    STX COPY_TO
    JSR COPY_FROM_TO_0
MANUAL_NEXT_LEVEL:
    LDX #FINISH_NEXT_TEXT
    STX COPY_FROM
    LDX #STATTEXT_LEVEL_ON_SCREEN+64     ; A szint sor eleje
    STX COPY_TO
    JSR COPY_FROM_TO_0
    JSR WAIT_FOR_YN_X_A
    CMPA #'Y
    BNE RESTART_LEVEL ; Ha nemet nyomott, akkor restart ez a szint
    JSR LEVEL_INC     ; Különben következő
    BRA RESTART_LEVEL

FINISH_TEXT: ;WAREHOUSE:
	.strz 'YOU HAVE ORGANISED THE WAREHAUSE'
FINISH_NEXT_TEXT: ;WAREHOUSE:
	.strz 'CAN YOU ORGANISE NEXT ONE? ' ; Length = 58
