	.area TOPTEXT (REL)

	.globl TOPTEXT,COPY_FROM,COPY_TO,COPY_FROM_TO_0
	.globl SOKOBAN_FIRST_LINE_ON_SCREEN ; From config

SHOWKOBAN::
    LDX #TOPTEXT
    STX COPY_FROM
    LDX #SOKOBAN_FIRST_LINE_ON_SCREEN
    STX COPY_TO
    JMP COPY_FROM_TO_0
